### ISSUE TITLE
Добавление/обновление/удаление данных в Справочнике

### ISSUE THREAD

**Issue by MiniJulia** [nemoware/procurement_transformation#8]
При получении информации о добавлении/обновлении/удалении данных в Справочнике (в оригинале) необходимо обновлять данные в копии Справочника.
Порядок получения информации описан в п.5.5. и п.5.6 ПР
[U200004739_ПР_по_интеграции_Модуля_автоформирования_КП_c_Mirror.docx](https://github.com/nemoware/procurement_transformation/files/8949499/U200004739_._._._._._._c_Mirror.docx)
.

**Comment by SergeyShalaevsky** [comment]
в итоге от этого отказались
